### ISSUE TITLE
4anime.to seems to be discontiniued

### ISSUE THREAD

**Issue by JairusSW** [fabriciopashaj/downloader-4anime#1]
Went to 4anime.to and saw this:
![image](https://user-images.githubusercontent.com/60235514/139746288-9891d3a3-f8c3-4259-8642-47bbceef98e0.png)

**Comment by JairusSW** [comment]
Looks like its going to be discontinued

**Comment by fabricio-p** [comment]
yeah, happened at the start of July. I should add some deprecation message, although no one would have used it. everyone just streams anime from the websites
